## config for snakemake CLIP mapping pipeline ##
## credit: Neel Mukherjee PARpipe (partially)


BOWTIE_INDEX:
  "phix/bowtie_idx"

PHIX:
  "phix/NC_001422.fna"

FA:
 "GRCh37.p13.genome.fa"

CHROM_SIZES:
 "GRCh37.p13.genome.fa.fai"

THREE_PRIME_ADAPTER_SEQUENCE:
  "TGGAATTCTCGGGTGCCAAGG"

REVERSE_PRIMER_SEQUENCE:
  "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG"

FORWARD_PRIMER_SEQUENCE:
  "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGACGATCCTGATC"

EASY_CLIP_FIVE_PRIME_ADAPTER_SEQUENCE:
  "GTTCAGAGTTCTACAGTCCGACGATCCTGATC"

NINETEEN_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGGTTTAAACGA"
TWENTY_FOUR_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGAATAGTTTAAACTGT"


THR:
  "4"


STAR_GENOME:
 "50bp_star_v2.7.3a"
  
GTF:
  "gencode.v19.annotation.gtf"

SEGE_IDX:
  "hg19.segemehl.idx"
